# Auto-generated by abaqus_case_tool
import sys
sys.path.insert(0, r"C:\Users\Lucien\Documents\Playground\abaqus_case_tool")

from abaqus_model_legacy import IntermediateCase, PostProcess

job_name = r"SmokeJob"
case = IntermediateCase(
    i=8.9,
    s=6.2,
    o=9.9,
    p=6.1,
    sub_job=False,
    job_name=job_name,
)
print("mass=", case.mass)
if False:
    print("result=", PostProcess(job_name).result)
